### ISSUE TITLE
Not working in Gutenberg?

### ISSUE THREAD

**Issue by ajuliano** [houke/acf-icon-picker#12]
I can't get the field to work in Gutenberg. The value/icon is not loaded after saving a post and reloading the edit screen.

I've added the field to a block that's been registered with acf_register_block_type (https://www.advancedcustomfields.com/resources/acf_register_block_type/).

**Comment by UnionDesign** [comment]
Same issue. I've looked at the code to attempt to fix it with no luck.

**Comment by houke** [comment]
Haven't tested it in Gutenberg so far, looking at a simple field from ACF itself (https://github.com/AdvancedCustomFields/acf/blob/master/includes/fields/class-acf-field-text.php) I see some changes there compared to this plugins field, so it is best to start looking there.

Two differences I see worth looking into: using `initialize()` instead of `__construct()` and `acf_register_field_type($class)` instead of `new Class()`.

I have this issue on my radar, but not sure yet when I'll follow up on this one.

**Comment by tlewap** [comment]
This pull request fix that https://github.com/houke/acf-icon-picker/pull/17
